version: '2.4'
services:
  node:
    tty: true
    stdin_open: true
    container_name: streams
    env_file:
      - ./.env
    build:
      context: .
      args:
        - NPM_TOKEN
    ports:
      - '31234:9229'
    user: 'node:node'
    volumes:
      - '.:/home/node/app:rw'
